# NumPy Features

## Продвинутые возможности и особенности библиотеки NumPy

## 1. Векторизация операций
<h4>1. Создать среду</h4>
<code>conda create -n np_env python=3.11</code>

<h4>2. Активировать среду</h4>
<code>conda activate np_env</code>

<h4>3. Установить библиотеки</h4>
<code>pip install numpy jupyter ipykernel</code>

<h4>4. Установить ядро для Jupyter (опционально)</h4>
<code>python -m ipykernel install --user --name=np_env --display-name="Python (np_env)"</code>


In [1]:
import numpy as np
import time

# Сравнение производительности
size = 1000000

# Python lists
py_list1 = list(range(size))
py_list2 = list(range(size))

start = time.time()
py_result = [a + b for a, b in zip(py_list1, py_list2)]
py_time = time.time() - start

# NumPy arrays
np_arr1 = np.arange(size)
np_arr2 = np.arange(size)

start = time.time()
np_result = np_arr1 + np_arr2
np_time = time.time() - start

print(f"Python list time: {py_time:.4f} seconds")
print(f"NumPy array time: {np_time:.4f} seconds")
print(f"Speedup: {py_time/np_time:.1f}x")

Python list time: 0.0721 seconds
NumPy array time: 0.0044 seconds
Speedup: 16.5x


## 2. Broadcasting - автоматическое расширение массивов

In [2]:
# Broadcasting примеры
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar = 10
vector = np.array([1, 2, 3])

print("Original array:")
print(arr)

print("\nArray + Scalar:")
print(arr + scalar)

print("\nArray + Vector (row):")
print(arr + vector)

print("\nArray + Vector (column):")
print(arr + vector.reshape(3, 1))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array + Scalar:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Array + Vector (row):
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Array + Vector (column):
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


## 3. Булева индексация

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Фильтрация элементов
even_numbers = arr[arr % 2 == 0]
greater_than_5 = arr[arr > 5]

print("Original array:", arr)
print("Even numbers:", even_numbers)
print("Numbers > 5:", greater_than_5)

# Множественные условия
condition = (arr > 3) & (arr < 8)
filtered = arr[condition]
print("Numbers between 3 and 8:", filtered)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]
Numbers > 5: [ 6  7  8  9 10]
Numbers between 3 and 8: [4 5 6 7]


## 4. Fancy Indexing

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original array:")
print(arr)

# Индексация списками
rows = [0, 2]
cols = [1, 2]
print("\nElements at [0,1] and [2,2]:", arr[rows, cols])

# Использование массивов для индексации
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
print("Diagonal from top-right:", arr[row_indices, col_indices])

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elements at [0,1] and [2,2]: [2 9]
Diagonal from top-right: [3 5 7]


## 5. Универсальные функции (ufunc)

In [5]:
x = np.array([0, np.pi/2, np.pi])

print("x:", x)
print("sin(x):", np.sin(x))
print("cos(x):", np.cos(x))
print("exp(x):", np.exp(x))
print("log(x+1):", np.log(x + 1))

# Агрегирующие ufunc
arr = np.array([1, 2, 3, 4, 5])
print("\nArray:", arr)
print("cumsum:", np.cumsum(arr))
print("cumprod:", np.cumprod(arr))

x: [0.         1.57079633 3.14159265]
sin(x): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(x): [ 1.000000e+00  6.123234e-17 -1.000000e+00]
exp(x): [ 1.          4.81047738 23.14069263]
log(x+1): [0.         0.94421571 1.42108041]

Array: [1 2 3 4 5]
cumsum: [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]


## 6. Линейная алгебра

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

print("\nMatrix multiplication:")
print(np.dot(A, B))

print("\nDeterminant of A:", np.linalg.det(A))
print("Inverse of A:")
print(np.linalg.inv(A))

print("\nEigenvalues and eigenvectors:")
eigenvals, eigenvecs = np.linalg.eig(A)
print("Eigenvalues:", eigenvals)
print("Eigenvectors:")
print(eigenvecs)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix multiplication:
[[19 22]
 [43 50]]

Determinant of A: -2.0000000000000004
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues and eigenvectors:
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 7. Работа с файлами

In [7]:
# Создание тестовых данных
data = np.random.random((5, 3))
print("Original data:")
print(data)

# Сохранение в файл
np.savetxt('data.csv', data, delimiter=',', fmt='%.3f')

# Загрузка из файла
loaded_data = np.loadtxt('data.csv', delimiter=',')
print("\nLoaded data:")
print(loaded_data)

# Сохранение в бинарном формате
np.save('data.npy', data)
binary_loaded = np.load('data.npy')
print("\nBinary loaded data:")
print(binary_loaded)

Original data:
[[0.93503492 0.38519508 0.91723447]
 [0.05715472 0.37523445 0.0093445 ]
 [0.72121468 0.06147952 0.27401206]
 [0.03519525 0.88518358 0.89392172]
 [0.73275162 0.16036094 0.61113046]]

Loaded data:
[[0.935 0.385 0.917]
 [0.057 0.375 0.009]
 [0.721 0.061 0.274]
 [0.035 0.885 0.894]
 [0.733 0.16  0.611]]

Binary loaded data:
[[0.93503492 0.38519508 0.91723447]
 [0.05715472 0.37523445 0.0093445 ]
 [0.72121468 0.06147952 0.27401206]
 [0.03519525 0.88518358 0.89392172]
 [0.73275162 0.16036094 0.61113046]]


## 8. Структурированные массивы

In [8]:
# Создание структурированного массива
dtype = [('name', 'U10'), ('age', 'i4'), ('score', 'f4')]
students = np.array([
    ('Alice', 20, 85.5),
    ('Bob', 22, 92.0),
    ('Charlie', 19, 78.5)
], dtype=dtype)

print("Structured array:")
print(students)

print("\nNames:", students['name'])
print("Ages:", students['age'])
print("Average score:", np.mean(students['score']))

# Сортировка по возрасту
sorted_by_age = np.sort(students, order='age')
print("\nSorted by age:")
print(sorted_by_age)

Structured array:
[('Alice', 20, 85.5) ('Bob', 22, 92. ) ('Charlie', 19, 78.5)]

Names: ['Alice' 'Bob' 'Charlie']
Ages: [20 22 19]
Average score: 85.333336

Sorted by age:
[('Charlie', 19, 78.5) ('Alice', 20, 85.5) ('Bob', 22, 92. )]


## 9. Маскированные массивы

In [9]:
import numpy.ma as ma

data = np.array([1, 2, -999, 4, 5, -999, 7])
# -999 представляет пропущенные значения

# Создание маскированного массива
masked_data = ma.masked_where(data == -999, data)

print("Original data:", data)
print("Masked data:", masked_data)
print("Mean (ignoring masked):", masked_data.mean())
print("Sum (ignoring masked):", masked_data.sum())

Original data: [   1    2 -999    4    5 -999    7]
Masked data: [1 2 -- 4 5 -- 7]
Mean (ignoring masked): 3.8
Sum (ignoring masked): 19


## Заключение

NumPy предоставляет мощные инструменты для эффективной работы с данными. Эти особенности делают его незаменимым для научных вычислений!